# Handle the Arithmetic exception using try-catch block

try:
    a=10
    b=0
    print(a/b)
except:
    print("this is Arithmetic Exception")